export const ENV = {
    PORT: process.env.PORT || 5000,
    MONGO_URI: process.env.MONGO_URI,
    JWT_SECRET: process.env.JWT_SECRET,
    JWT_EXPIRES_IN: process.env.JWT_EXPIRES_IN || '7d',
    CLIENT_URL: process.env.CLIENT_URL || 'https://317am.vercel.app/',
    COOKIE_NAME: process.env.COOKIE_NAME || '317am_session',
    COOKIE_MAX_AGE: 7 * 24 * 60 * 60 * 1000,
    NODE_ENV: process.env.NODE_ENV || 'development',

    EMAIL_PROVIDER: process.env.EMAIL_PROVIDER || 'smtp',
    EMAIL_FROM: process.env.EMAIL_FROM || '317am.archive@gmail.com',
    EMAIL_USER: process.env.EMAIL_USER,
    EMAIL_PASS: process.env.EMAIL_PASS,
    RESEND_API_KEY: process.env.RESEND_API_KEY,
    SMTP_HOST: process.env.SMTP_HOST,
    SMTP_PORT: process.env.SMTP_PORT || '587',
    SMTP_USER: process.env.SMTP_USER,
    SMTP_PASS: process.env.SMTP_PASS,
};